---
- name: Install Ansible
  package:
    name: ansible
    state: latest

- name: Install git
  package:
    name: git
    state: latest

- name: Install unzip
  package:
    name: unzip
    state: latest
    
- name: Copy ansible.cfg file to home dir
  copy:
    src: "{{ deploy_folder }}/ansible.cfg"
    dest: ~/.ansible.cfg

- name: Copy ansible.cfg file to /etc/ansible/
  copy:
    src: "{{ deploy_folder }}/ansible.cfg"
    dest: /etc/ansible/ansible.cfg