---
# Use it for test
# export CLUSTER_NAME=fri
# ansible-playbook -i ~/hosts-${CLUSTER_NAME} main.yml --extra-vars "@extra_vars.yml"
debug: true
github_url: https://github.com/frischHWC/random-datagen
cdp_version: 7.1.7

hadoop_user: dev
hadoop_home: /user/dev
kerb_auth: true
kerb_user: dev
kerb_keytab: /home/dev/dev.keytab

truststore_location: /tmp/truststore.jks

cloudera_manager_truststore_password: PKL2vpqpyCaoTBNFDhTNevfdNcXvCkircUZapAzVZw0
hdfs_nameservice: hdfs://fri:8020/
zk_quorum_with_port: ccycloud-3.fri.root.hwx.site:2181,ccycloud-4.fri.root.hwx.site:2181,ccycloud-2.fri.root.hwx.site:2181
ozone_service_id: fri
solr_url: https://ccycloud-10.fri.root.hwx.site
solr_port:
solr_ssl: True
kudu_url: ccycloud-2.fri.root.hwx.site,ccycloud-4.fri.root.hwx.site,ccycloud-3.fri.root.hwx.site
kafka_url: ccycloud-9.fri.root.hwx.site:9092,ccycloud-8.fri.root.hwx.site:9092,ccycloud-10.fri.root.hwx.site:9092
kafka_protocol: SASL_SSL
keystore: /var/lib/cloudera-scm-agent/agent-cert/cm-auto-host_keystore.jks
keystore_pass: changeme
keystore_key_pass: changeme
sr_url: ccycloud-3.fri.root.hwx.site


gen_hdfs: true
gen_solr: false
gen_kudu: false

gen_hbase: false
gen_ozone: false
gen_hive: false
gen_kafka: false