---
cloudera_manager_host: ${NODE_0} 
cloudera_manager_user: admin 
cloudera_manager_password: admin 
cluster_name: ${CLUSTER_NAME} 
auto_tls: ${TLS} 
encryption_activated: ${ENCRYPTION_ACTIVATED}
cluster_type: ${CLUSTER_TYPE} 
free_ipa: ${FREE_IPA} 
ipaadmin_password: ${DEFAULT_PASSWORD} 
realm: ${REALM} 
ranger_user: admin 
ranger_password: ${DEFAULT_PASSWORD} 
default_password: ${DEFAULT_PASSWORD} 
debug: ${DEBUG}
use_wxm: ${USE_WXM}
altus_key_id: ${ALTUS_KEY_ID}
altus_private_key: ${ALTUS_PRIVATE_KEY}
cloudera_manager_base_url: ${CM_BASE_URL}
cloudera_manager_base_user: ${CM_BASE_USER}
cloudera_manager_base_password: ${CM_BASE_PASSWORD}
tp_host: ${TP_HOST}