---
- name: CM Configuration post-install no unlog and fix TLS settings
  hosts: main
  gather_facts: false
  roles: 
    - no-unlog
    - restart_cm

- name: Check existing services
  hosts: all
  gather_facts: false
  roles: 
    - check_solr_hue_service

- name: Fix krb5.conf for Hue with Free IPA
  hosts: all
  gather_facts: false
  roles: 
    - { role: hue_free_ipa_krb5conf, when: free_ipa and hue_service_exists }

- name: Fix Hue ticket lifetime for Free IPA
  hosts: main
  gather_facts: false
  roles: 
    - { role: hue_free_ipa_ticket_lifetime, when: free_ipa and hue_service_exists }

- name: Create missing SolR plugin for Ranger
  hosts: main
  gather_facts: false
  roles: 
    - { role: fix_solr_plugin, when: solr_service_exists }

- name: Add Solr urls to Knox
  hosts: main
  gather_facts: false
  roles: 
    - { role: add_solr_knox, when: solr_service_exists }

- name: Add missing TLS values for Ranger KMS
  hosts: main
  gather_facts: false
  roles: 
    - { role: fix_kms_tls, when: encryption_activated }

- name: Ranger extra policies to have enough rights with basic accounts
  hosts: main
  gather_facts: false
  roles: 
    - ranger_extra_policies
