---
- name: CM Configuration post-install no unlog and fix TLS settings
  hosts: main
  gather_facts: false
  roles: 
    - no-unlog
    - restart_cm

- name: Check existing services
  hosts: all
  gather_facts: false
  roles: 
    - check_existing_services

- name: Fix krb5.conf for Hue with Free IPA
  hosts: all
  gather_facts: false
  roles: 
    - { role: hue_free_ipa_krb5conf, when: free_ipa and hue_service_exists | default(false) }

- name: Fix Hue ticket lifetime for Free IPA
  hosts: main
  gather_facts: false
  roles: 
    - { role: hue_free_ipa_ticket_lifetime, when: free_ipa and hue_service_exists | default(false) }

- name: Create missing SolR plugin for Ranger
  hosts: main
  gather_facts: false
  roles: 
    - { role: fix_solr_plugin, when: solr_service_exists | default(false) }

- name: Add Solr urls to Knox
  hosts: main
  gather_facts: false
  roles: 
    - { role: add_solr_knox, when: solr_service_exists | default(false) }

- name: Add missing TLS values for Ranger KMS
  hosts: main
  gather_facts: false
  roles: 
    - { role: fix_kms_tls, when: encryption_activated | default(false) }

- name: Add missing ExtJS for Oozie
  hosts: all
  gather_facts: false
  roles: 
    - { role: fix_oozie_ui, when: oozie_service_exists | default(false) }

- name: Pre-Configure WXM
  hosts: main, tp_host
  gather_facts: false
  roles: 
    - { role: wxm_config, when: use_wxm | default(false) }

- name: Configure Telemetry for WXM
  hosts: tp_host
  gather_facts: false
  roles: 
    - { role: wxm_configure_telemetry, when: use_wxm | default(false) }
    - { role: wxm_truststore_to_base, when: use_wxm | default(false) }

- name: Restart WXM and Services
  hosts: main
  gather_facts: false
  roles: 
    - { role: wxm_restart, when: use_wxm | default(false) }

- name: Ranger extra policies to have enough rights with basic accounts
  hosts: main
  gather_facts: false
  roles: 
    - { role: ranger_extra_policies, when: ranger_service_exists }
