---
- name: Adding enctypes and renewable ticket lifetime
  blockinfile:
    dest: "/etc/krb5.conf"
    insertafter: 'ticket_lifetime = 24h'
    block: |
      default_tgs_enctypes= aes256-cts-hmac-sha1-96 arcfour-hmac aes128-cts-hmac-sha1-96 des-cbc-md5
      default_tkt_enctypes = aes256-cts-hmac-sha1-96 arcfour-hmac aes128-cts-hmac-sha1-96 des-cbc-md5
      renew_lifetime = 7d
      max_life = 365d
      max_renewable_life = 365d
  ignore_errors: true

- name: Comment default_ccache_name in krb5.conf
  replace:
    dest: /etc/krb5.conf
    regexp: 'default_ccache_name = KEYRING:persistent:%{uid}'
    replace: '#default_ccache_name = KEYRING:persistent:%{uid}'
  ignore_errors: true
