---
distribution: ${DISTRIBUTION_TO_DEPLOY} 
debug: ${DEBUG} 
free_ipa: ${FREE_IPA} 
cluster_name: ${CLUSTER_NAME}
etc_hosts_file: ${HOSTS_ETC}
known_hosts: ${KNOWN_HOSTS}
license_file: ${LICENSE_FILE}
authorized_keys: ${AUTHORIZED_KEYS}
node_key: ${NODE_KEY}
