---
- name: Check CM is no-TLS
  uri:
    url: "http://{{ cloudera_manager_host }}:7180/"
    user: "{{ cloudera_manager_user }}"
    password: "{{ cloudera_manager_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200, -1
    return_content: yes
    validate_certs: no
  register: cluster_deployment

- name: DEBUG - API Call
  debug:
    msg: "{{ cluster_deployment }}"
  when: debug | default(false)

- set_fact:
    cloudera_manager_protocol: http
    cloudera_manager_port: 7180
  when: cluster_deployment.status == 200


- name: Check CM is TLS
  uri:
    url: "https://{{ cloudera_manager_host }}:7183/"
    user: "{{ cloudera_manager_user }}"
    password: "{{ cloudera_manager_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200, -1
    return_content: yes
    validate_certs: no
  register: cluster_deployment

- name: DEBUG - API Call
  debug:
    msg: "{{ cluster_deployment }}"
  when: debug | default(false)

- set_fact:
    cloudera_manager_protocol: https
    cloudera_manager_port: 7183
  when: cluster_deployment.status == 200


- set_fact:
    cloudera_manager_url: "{{ cloudera_manager_protocol }}://{{ cloudera_manager_host }}:{{ cloudera_manager_port }}"

- name: Get CM API Version
  uri:
    url: "{{ cloudera_manager_url }}/api/version"
    user: "{{ cloudera_manager_user }}"
    password: "{{ cloudera_manager_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    return_content: yes
    validate_certs: no
    body_format: json
  register: cloudera_manager_api_version_response

- set_fact:
    cloudera_manager_api_version: "{{ cloudera_manager_api_version_response.content }}"

- set_fact:
    cloudera_manager_api_url: "{{ cloudera_manager_url }}/api/{{ cloudera_manager_api_version }}"