---
# Install Kubectl on CM to interact with cluster
- name: Get kubectl latest release
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
    follow_redirects: all
  register: kubectl_version

- name: DEBUG - kubectl_version
  debug:
    msg: "{{ kubectl_version }}"
  when: debug | default(false)

- name: Download kubectl binary
  uri:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
    return_content: yes
    follow_redirects: all
    status_code: [200, 304]
    dest: ~/kubectl

- name: Copy kubectl file to binary place 
  copy:
    src: ~/kubectl
    dest: /usr/local/bin/ 
    mode: 0755
    remote_src: yes

# Setup kubeconfig to be able to launch kube commands from Management Node
- name: Copy the kubeconfig 
  copy:
    src: "/tmp/kubeconfig/{{ pvc_ecs_server_host }}/etc/rancher/rke2/rke2.yaml"
    dest: "/root/kubeconfig"

- name: Replace in kubeconfig the pvc_ecs_server_host
  replace:
    path: /root/kubeconfig
    regexp: "127.0.0.1"
    replace: "{{ pvc_ecs_server_host }}"

- name: Insert KUBECONFIG vars to bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      export KUBECONFIG=/root/kubeconfig
