---
# Set CM URLs for WXM cluster
- set_fact:
    cloudera_manager_protocol: http
    cloudera_manager_port: 7180
  when: not auto_tls

- set_fact:
    cloudera_manager_protocol: https
    cloudera_manager_port: 7183
  when: auto_tls

- set_fact:
    cloudera_manager_url: "{{ cloudera_manager_protocol }}://{{ cloudera_manager_host }}:{{ cloudera_manager_port }}"

- name: Get CM API Version
  uri:
    url: "{{ cloudera_manager_url }}/api/version"
    user: "{{ cloudera_manager_user }}"
    password: "{{ cloudera_manager_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    return_content: yes
    validate_certs: no
    body_format: json
  register: cloudera_manager_api_version_response

- set_fact:
    cloudera_manager_api_version: "{{ cloudera_manager_api_version_response.content }}"

- set_fact:
    cloudera_manager_api_url: "{{ cloudera_manager_url }}/api/{{ cloudera_manager_api_version }}"

- name: DEBUG - cloudera_manager_api_url
  debug:
    msg: "{{ cloudera_manager_api_url }}"
  when: debug | default(false)

# Get WXM host and service name
- name: Get All services from CM
  uri:
    url: "{{ cloudera_manager_api_url }}/clusters/{{ cluster_name }}/services/"
    user: "{{ cloudera_manager_user }}"
    password: "{{ cloudera_manager_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    return_content: yes
    validate_certs: no
    body_format: json
  register: cloudera_manager_wxm_all_services

- set_fact:
    wxm_service_name: "{{ cloudera_manager_wxm_all_services.json | community.general.json_query(query) }}"
  vars:
    query: "items[?type == 'WXM'].name | [0]"

- name: DEBUG - wxm_service_name
  debug:
    msg: "{{ wxm_service_name }}"
  when: debug | default(false)

- name: Get detailed service WXM from CM
  uri:
    url: "{{ cloudera_manager_api_url }}/clusters/{{ cluster_name }}/services/{{ wxm_service_name }}/roles"
    user: "{{ cloudera_manager_user }}"
    password: "{{ cloudera_manager_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    return_content: yes
    validate_certs: no
    body_format: json
  register: cloudera_manager_wxm_all_roles

- set_fact:
    wxm_api_server: "{{ cloudera_manager_wxm_all_roles.json | community.general.json_query(query) }}"
  vars:
    query: "items[?type == 'DBUS_API_SERVICE'].hostRef.hostname | [0]"

- name: DEBUG - wxm_api_server
  debug:
    msg: "{{ wxm_api_server }}"
  when: debug | default(false)


- name: Get detailed config WXM from CM
  uri:
    url: "{{ cloudera_manager_api_url }}/clusters/{{ cluster_name }}/services/{{ wxm_service_name }}/roleConfigGroups/{{ wxm_service_name }}-THUNDERHEAD_SIGMA_CONSOLE-BASE/config?view=full"
    user: "{{ cloudera_manager_user }}"
    password: "{{ cloudera_manager_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    return_content: yes
    validate_certs: no
    body_format: json
  register: cloudera_manager_wxm_all_roles

- set_fact:
    wxm_ssl_enabled: "{{ cloudera_manager_wxm_all_roles.json | community.general.json_query(query) }}"
  vars:
    query: "items[?name == 'ssl_enabled'].value | [0]"

- set_fact:
    wxm_ssl_enabled: "{{ cloudera_manager_wxm_all_roles.json | community.general.json_query(query) }}"
  vars:
    query: "items[?name == 'ssl_enabled'].default | [0]"
  when: wxm_ssl_enabled == ''
  
- name: DEBUG - wxm_ssl_enabled
  debug:
    msg: "{{ wxm_ssl_enabled }}"
  when: debug | default(false)

- name: Set WXM Databus API server URL 
  set_fact:
    wxm_dbus_api_server_url: "https://{{ wxm_api_server }}:12022/"
  when: wxm_ssl_enabled

- name: Set WXM Databus API server URL 
  set_fact:
    wxm_dbus_api_server_url: "http://{{ wxm_api_server }}:12022/"
  when: not wxm_ssl_enabled

- name: DEBUG - wxm_dbus_api_server_url
  debug:
    msg: "{{ wxm_dbus_api_server_url }}"
  when: debug | default(false)

# Set CM URLs for base cluster to associate with WXM

- name: Check if needed to configure WXM 
  set_fact: 
    configure_wxm_with_base: "{{ true if cloudera_manager_base_url != '' else false }}"

- name: Get CM API Version
  uri:
    url: "{{ cloudera_manager_base_url }}/api/version"
    user: "{{ cloudera_manager_base_user }}"
    password: "{{ cloudera_manager_base_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    return_content: yes
    validate_certs: no
    body_format: json
  register: cloudera_manager_base_api_version_response
  when: configure_wxm_with_base

- set_fact:
    cloudera_manager_base_api_version: "{{ cloudera_manager_base_api_version_response.content }}"
  when: configure_wxm_with_base

- set_fact:
    cloudera_manager_base_api_url: "{{ cloudera_manager_base_url }}/api/{{ cloudera_manager_base_api_version }}"
  when: configure_wxm_with_base

- name: DEBUG - cloudera_manager_base_api_url
  debug:
    msg: "{{ cloudera_manager_base_api_url }}"
  when: configure_wxm_with_base and debug | default(false)