---
####### PvC pre-requisites and fixes to make before setting up PvC #######

# Required Packages
- name: Install python 3
  package:
    name: python3
    state: present

- name: Install pip3
  package:
    name: python3-pip
    state: present

- name: Install cdpcli
  pip:
    name: cdpcli>=0.9.54
    executable: pip3

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Install gunzip
  package:
    name: unzip
    state: present

# Apply Patch to generate_crendentials for FreeIPA
- set_fact: 
    cp_domain: "{{ (lookup('template', kube_config_path ) | from_yaml).clusters[0].cluster.server.split('//')[1].split(':')[0].replace('api.', '') }}"
  when: pvc_type == "OC"

- set_fact: 
    cp_domain: "{{ pvc_ecs_server_host }}"
  when: pvc_type == "ECS"

- name: DEBUG - cp_domain
  debug:
    msg: "{{ cp_domain }}"
  when: debug | default(false)


- name: Template Patch to CM 7.4 host
  template:
    src: gen_credentials_ipa_cm75.p
    dest: /tmp/gen_credentials.p
  when: cm_version.split('.')[1] == '4'

- name: Template Patch to CM 7.5 host
  template:
    src: gen_credentials_ipa_cm75.p
    dest: /tmp/gen_credentials_ipa.p
  when: cm_version.split('.')[1] == '5' or cm_version.split('.')[1] == '6'

- name: Apply patch remotely
  patch:
    src: /tmp/gen_credentials_ipa.p
    dest: /opt/cloudera/cm/bin/gen_credentials_ipa.sh
    remote_src: yes
    backup: yes

# Correct krb5.conf 

- name: Comment include dir lines of /etc/krb5.conf
  replace:
    path: /etc/krb5.conf
    regexp: '^(includedir)'
    replace: '#\1'

- name: Resolve ipa_server's IP
  shell: "cat /etc/hosts | grep -m 1 {{ ipa_server }} | cut -d' ' -f1 | xargs"
  register: ipa_server_ip_resolve

- name: DEBUG - ipa_server's IP
  debug:
    msg: "{{ ipa_server_ip_resolve }}"
  when: debug | default(false)

- name: Resolve ipa_server's IP
  set_fact: 
    ipa_server_ip: "{{ ipa_server_ip_resolve.stdout }}"

- name: DEBUG - ipa_server's IP
  debug:
    msg: "{{ ipa_server_ip }}"
  when: debug | default(false)

- name: Replace IPA's server hostname with IP
  replace:
    path: /etc/krb5.conf
    regexp: "{{ ipa_server }}"
    replace: "{{ ipa_server_ip }}"


# Download and set up cdp-cde-utils.tgz

- name: Download cdp-cde-utils.sh.gz
  get_url:
    url: "https://docs.cloudera.com/data-engineering/1.3.4/cdp-cde-utils.sh"
    dest: ~/cdp-cde-utils.sh
    mode: '0775'
  ignore_errors: true
    
- name: Set cdp-cde script executable
  file:
    path: ~/cdp-cde-utils.sh
    mode: '0775'
  ignore_errors: true
