---
- name: Post Ranger policies declared in policies directory
  uri: 
    url: "{{ ranger_url }}/service/public/v2/api/policy"
    method: POST
    user: "{{ ranger_user }}"
    password: "{{ ranger_password }}"
    return_content: yes
    body: "{{ lookup('template', '{{ item.src }}' ) }}"
    body_format: json
    status_code: 200
    validate_certs: no
    force_basic_auth: yes
  with_filetree: "{{ role_path }}/policies"
  ignore_errors: yes
